---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/MyHelmSampleApp
  type: udm.Application
  lastVersion: 3.0.2
  children:
  - name: 3.0.1
    type: udm.DeploymentPackage
    deployables:
    - name: tomcat
      type: helm.Chart
      chartName: bitnami/tomcat
      repositoryUrl: https://charts.bitnami.com/bitnami
      chartVersion: 6.3.12
      testRelease: True
      inputVariables:
        tomcatUsername: scott
      secretInputVariables:
        tomcatPassword: tiger
  - name: 3.0.2
    type: udm.DeploymentPackage
    orchestrator:
    - parallel-by-deployed
    deployables:   
    - name: mariadb
      type: helm.Chart
      chartName: bitnami/mariadb
      chartVersion: 7.6.1
      repositoryUrl: https://charts.bitnami.com/bitnami
      testRelease: False
      inputVariables:
        db.name: petclinic
        replication.enabled: false
        master.persistence.size: 1Mi
      configurationFiles:
      - name: config.yaml
        type: helm.ConfigFile
        file: !file "artifacts/config.yaml"
    - name: tomcat
      type: helm.Chart
      chartName: bitnami/tomcat
      repositoryUrl: https://charts.bitnami.com/bitnami
      chartVersion: 6.3.12
      testRelease: True
      inputVariables:
        tomcatUsername: scott
      secretInputVariables:
        tomcatPassword: tiger
  - name: 3.0.0
    type: udm.DeploymentPackage
    deployables:
    - name: tomcat
      type: helm.Chart
      chartName: bitnami/tomcat
      repositoryUrl: https://charts.bitnami.com/bitnami
      chartVersion: 6.3.11
      testRelease: True
      inputVariables:
        tomcatUsername: scott
      secretInputVariables:
        tomcatPassword: tiger